name: Deploy Frontend (dev)

on:
  push:
    branches: [ dev ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v5

      - name: Configurar Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'

      - name: Instalar Dependências
        run: npm ci

      - name: Instalar o Quasar CLI Globalmente
        run: npm install -g @quasar/cli

      - name: Compilar o Projeto (Build)
        run: quasar build

      - name: Configurar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DM_FRONT_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -p 22 ${{ secrets.DM_FRONT_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Enviar Arquivos para o Servidor via Rsync/SSH
        run: |
          rsync -avzr --delete \
            -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no -p 22" \
            dist/spa/ ${{ secrets.DM_FRONT_SSH_USER }}@${{ secrets.DM_FRONT_SSH_HOST }}:${{ secrets.DM_FRONT_DEPLOY_PATH }}