name: Deploy Frontend (dev)

on:
  push:
    branches: [ dev ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v5

      - name: Configurar Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'

      - name: Instalar Dependências
        run: npm ci

      - name: Instalar o Quasar CLI Globalmente
        run: npm install -g @quasar/cli

      - name: Compilar o Projeto (Build)
        run: APP_ENV=development quasar build -m spa

      - name: Configurar SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DM_FRONT_SSH_KEY }}

      - name: Enviar Arquivos para o Servidor via Rsync/SSH
        run: |
          rsync -avzr --delete \
            -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 22" \
            dist/spa/ ${{ secrets.DM_FRONT_SSH_USER }}@${{ secrets.DM_FRONT_SSH_HOST }}:${{ secrets.DM_FRONT_DEPLOY_PATH }}